
options:
    docker: true
clone:
  depth: full

definitions: 
  steps:

    - nexus-template: &nexus-template        
        image: atlassian/default-image:3
        name: Get setting.xml template for compile
        max-time: 20
        script:
          - git clone https://x-token-auth:$BITBUCKET_TEMPLATE_TOKEN@bitbucket.org/directa24/bitbucket-pipe-templates.git
        artifacts:
          - bitbucket-pipe-templates/**

    - java-release: &java-release
        image: maven:3.8.5-amazoncorretto-17
        name: Maven Release
        script:
          - yum install -y git
          - git clone https://$BITBUCKET_PIPE_USER:$BITBUCKET_PIPE_USER_PWD@bitbucket.org/directa24/$BITBUCKET_REPO_SLUG.git release
          - git config --global user.email "infra+devops@d24.com"
          - git config --global user.name "Bitbucket-user-pipe" 
          - cd release
          #Remove SNAPSHOT release on master
          - git checkout master
          - mvn -X -s ../bitbucket-pipe-templates/settings.xml versions:set -DgenerateBackupPoms=false -DremoveSnapshot=true
          - export RELEASE_VERSION=$(mvn -s ../bitbucket-pipe-templates/settings.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          - git add .
          - git commit -m "[skip ci] Upgrade release version to $RELEASE_VERSION - id trigger $BITBUCKET_BUILD_NUMBER"
          - git push
          #Create Tag release
          - git tag $RELEASE_VERSION
          - git push origin $RELEASE_VERSION
          #Upgrade release on develop
          - git checkout develop
          - git pull origin master
          - mvn -X -s ../bitbucket-pipe-templates/settings.xml build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}-SNAPSHOT -DgenerateBackupPoms=false
          - export RELEASE_VERSION=$(mvn -s ../bitbucket-pipe-templates/settings.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          - git add .
          - git commit -m "[skip ci] Upgrade release version to $RELEASE_VERSION - id trigger $BITBUCKET_BUILD_NUMBER"
          - git push

    - github-sync: &github-sync      
        image: atlassian/default-image:3
        name: Remove pipe and push github
        script:
          - git clone https://$BITBUCKET_PIPE_USER:$BITBUCKET_PIPE_USER_PWD@bitbucket.org/directa24/$BITBUCKET_REPO_SLUG.git bitbucket_tmp
          #- rm bitbucket_tmp/bitbucket-pipelines.yml
          - export GITHUB_USER=directa24
          - export GITHUB_TOKEN=$GITHUB_TOKEN
          - export GITHUB_REPOSITORY=directa24/cashin-java-sdk.git
          - git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} github_tmp
          - git config --global user.email "infra+devops@d24.com"
          - git config --global user.name "Bitbucket-user-pipe" 
          - git checkout master
          - cp -fR bitbucket_tmp/* github_tmp
          - cd github_tmp
          - rm bitbucket-pipelines.yml
          - git commit -a -m "github sync"
          #- ls -lrt
          - git push

pipelines:
  branches:
    master:
      - step: *nexus-template
      - step: *java-release
      - step: *github-sync